title: "Le Blog de la Société TreeptiK | Cloud Computing | Développement Java EE | Virtualisation"
url: "http://blog.treeptik.fr"
author: "treeptik-team"
email: "contact@treeptik.fr"
description: "Toute l'actualité du Cloud Computing et le développement d'applications Java JEE"

paginate: 5


permalink: /:year/:month/:title

markdown: rdiscount
highlighter: pygments

exclude:
  - README.markdown
  - _drafts

production_url : http://blog.treeptik.fr

tag_page_layout: tag_page
tag_page_dir: tag
base: "http://www.treeptik.fr"
