title: "Treeptik Blog"
url: "http://blog.treeptik.fr"
author: "treeptik-team"
email: "contact@treeptik.fr"
description: "Blog des ingénieurs de treeptik"

auto: false
paginate: 5
paginate_files:
 - index.html

permalink: /:year/:month/:title

markdown: rdiscount
pygments: true

exclude:
  - README.markdown
  - _drafts

production_url : http://blog.treeptik.fr

tag_page_layout: tag_page
tag_page_dir: tag
